// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: comment/comment.proto

package comment

import (
	menu_item "github.com/Architech-App/PlateModel/menu_item"
	user "github.com/Architech-App/PlateModel/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint32                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating           uint32                     `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Text             string                     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreationDate     string                     `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	User             *user.UserDB               `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	CommentMenuItems []*menu_item.WrapMenuItems `protobuf:"bytes,6,rep,name=comment_menu_items,json=commentMenuItems,proto3" json:"comment_menu_items,omitempty"`
}

func (x *CommentDB) Reset() {
	*x = CommentDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentDB) ProtoMessage() {}

func (x *CommentDB) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentDB.ProtoReflect.Descriptor instead.
func (*CommentDB) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentDB) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentDB) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CommentDB) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentDB) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CommentDB) GetUser() *user.UserDB {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CommentDB) GetCommentMenuItems() []*menu_item.WrapMenuItems {
	if x != nil {
		return x.CommentMenuItems
	}
	return nil
}

type WrapComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment *CommentDB `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *WrapComment) Reset() {
	*x = WrapComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WrapComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapComment) ProtoMessage() {}

func (x *WrapComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapComment.ProtoReflect.Descriptor instead.
func (*WrapComment) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{1}
}

func (x *WrapComment) GetComment() *CommentDB {
	if x != nil {
		return x.Comment
	}
	return nil
}

var File_comment_comment_proto protoreflect.FileDescriptor

var file_comment_comment_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2f, 0x6d, 0x65,
	0x6e, 0x75, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x42, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x42, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x45, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65,
	0x6e, 0x75, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x57, 0x72, 0x61, 0x70, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3c, 0x0a, 0x0b, 0x57, 0x72, 0x61,
	0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x42, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x68, 0x2d,
	0x41, 0x70, 0x70, 0x2f, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comment_comment_proto_rawDescOnce sync.Once
	file_comment_comment_proto_rawDescData = file_comment_comment_proto_rawDesc
)

func file_comment_comment_proto_rawDescGZIP() []byte {
	file_comment_comment_proto_rawDescOnce.Do(func() {
		file_comment_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_comment_comment_proto_rawDescData)
	})
	return file_comment_comment_proto_rawDescData
}

var file_comment_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comment_comment_proto_goTypes = []interface{}{
	(*CommentDB)(nil),               // 0: protobuf.CommentDB
	(*WrapComment)(nil),             // 1: protobuf.WrapComment
	(*user.UserDB)(nil),             // 2: protobuf.UserDB
	(*menu_item.WrapMenuItems)(nil), // 3: protobuf.WrapMenuItems
}
var file_comment_comment_proto_depIdxs = []int32{
	2, // 0: protobuf.CommentDB.user:type_name -> protobuf.UserDB
	3, // 1: protobuf.CommentDB.comment_menu_items:type_name -> protobuf.WrapMenuItems
	0, // 2: protobuf.WrapComment.comment:type_name -> protobuf.CommentDB
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_comment_comment_proto_init() }
func file_comment_comment_proto_init() {
	if File_comment_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comment_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WrapComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comment_comment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comment_comment_proto_goTypes,
		DependencyIndexes: file_comment_comment_proto_depIdxs,
		MessageInfos:      file_comment_comment_proto_msgTypes,
	}.Build()
	File_comment_comment_proto = out.File
	file_comment_comment_proto_rawDesc = nil
	file_comment_comment_proto_goTypes = nil
	file_comment_comment_proto_depIdxs = nil
}
