// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: hasurapb/hasuraRequest.proto

package hasurapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasuraRequestHeaders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=Authorization,proto3" json:"Authorization,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Origin        string `protobuf:"bytes,3,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Referer       string `protobuf:"bytes,4,opt,name=Referer,proto3" json:"Referer,omitempty"`
	Accept        string `protobuf:"bytes,5,opt,name=Accept,proto3" json:"Accept,omitempty"`
	Connection    string `protobuf:"bytes,6,opt,name=Connection,proto3" json:"Connection,omitempty"`
	DNT           string `protobuf:"bytes,7,opt,name=DNT,proto3" json:"DNT,omitempty"`
}

func (x *HasuraRequestHeaders) Reset() {
	*x = HasuraRequestHeaders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasurapb_hasuraRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasuraRequestHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasuraRequestHeaders) ProtoMessage() {}

func (x *HasuraRequestHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_hasurapb_hasuraRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasuraRequestHeaders.ProtoReflect.Descriptor instead.
func (*HasuraRequestHeaders) Descriptor() ([]byte, []int) {
	return file_hasurapb_hasuraRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HasuraRequestHeaders) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *HasuraRequestHeaders) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HasuraRequestHeaders) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *HasuraRequestHeaders) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *HasuraRequestHeaders) GetAccept() string {
	if x != nil {
		return x.Accept
	}
	return ""
}

func (x *HasuraRequestHeaders) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *HasuraRequestHeaders) GetDNT() string {
	if x != nil {
		return x.DNT
	}
	return ""
}

type HasuraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers *HasuraRequestHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
}

func (x *HasuraRequest) Reset() {
	*x = HasuraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasurapb_hasuraRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasuraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasuraRequest) ProtoMessage() {}

func (x *HasuraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hasurapb_hasuraRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasuraRequest.ProtoReflect.Descriptor instead.
func (*HasuraRequest) Descriptor() ([]byte, []int) {
	return file_hasurapb_hasuraRequest_proto_rawDescGZIP(), []int{1}
}

func (x *HasuraRequest) GetHeaders() *HasuraRequestHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_hasurapb_hasuraRequest_proto protoreflect.FileDescriptor

var file_hasurapb_hasuraRequest_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x68, 0x61, 0x73, 0x75, 0x72, 0x61, 0x70, 0x62, 0x2f, 0x68, 0x61, 0x73, 0x75, 0x72,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xcc, 0x01, 0x0a, 0x14, 0x48, 0x61, 0x73,
	0x75, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x4e, 0x54, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x44, 0x4e, 0x54, 0x22, 0x49, 0x0a, 0x0d, 0x48, 0x61, 0x73, 0x75, 0x72,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x48, 0x61, 0x73, 0x75, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x68, 0x61, 0x73, 0x75, 0x72, 0x61, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hasurapb_hasuraRequest_proto_rawDescOnce sync.Once
	file_hasurapb_hasuraRequest_proto_rawDescData = file_hasurapb_hasuraRequest_proto_rawDesc
)

func file_hasurapb_hasuraRequest_proto_rawDescGZIP() []byte {
	file_hasurapb_hasuraRequest_proto_rawDescOnce.Do(func() {
		file_hasurapb_hasuraRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_hasurapb_hasuraRequest_proto_rawDescData)
	})
	return file_hasurapb_hasuraRequest_proto_rawDescData
}

var file_hasurapb_hasuraRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hasurapb_hasuraRequest_proto_goTypes = []interface{}{
	(*HasuraRequestHeaders)(nil), // 0: protobuf.HasuraRequestHeaders
	(*HasuraRequest)(nil),        // 1: protobuf.HasuraRequest
}
var file_hasurapb_hasuraRequest_proto_depIdxs = []int32{
	0, // 0: protobuf.HasuraRequest.headers:type_name -> protobuf.HasuraRequestHeaders
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hasurapb_hasuraRequest_proto_init() }
func file_hasurapb_hasuraRequest_proto_init() {
	if File_hasurapb_hasuraRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hasurapb_hasuraRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasuraRequestHeaders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hasurapb_hasuraRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasuraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hasurapb_hasuraRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hasurapb_hasuraRequest_proto_goTypes,
		DependencyIndexes: file_hasurapb_hasuraRequest_proto_depIdxs,
		MessageInfos:      file_hasurapb_hasuraRequest_proto_msgTypes,
	}.Build()
	File_hasurapb_hasuraRequest_proto = out.File
	file_hasurapb_hasuraRequest_proto_rawDesc = nil
	file_hasurapb_hasuraRequest_proto_goTypes = nil
	file_hasurapb_hasuraRequest_proto_depIdxs = nil
}
