// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: nearby/nearby.proto

package nearby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NearbyInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *NearbyInput) Reset() {
	*x = NearbyInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyInput) ProtoMessage() {}

func (x *NearbyInput) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyInput.ProtoReflect.Descriptor instead.
func (*NearbyInput) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{0}
}

func (x *NearbyInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NearbyUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserRestrictions []*NearbyUserRestrictions `protobuf:"bytes,2,rep,name=user_restrictions,json=userRestrictions,proto3" json:"user_restrictions,omitempty"`
}

func (x *NearbyUser) Reset() {
	*x = NearbyUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUser) ProtoMessage() {}

func (x *NearbyUser) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUser.ProtoReflect.Descriptor instead.
func (*NearbyUser) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NearbyUser) GetUserRestrictions() []*NearbyUserRestrictions {
	if x != nil {
		return x.UserRestrictions
	}
	return nil
}

type NearbyUserRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestrictionId uint32 `protobuf:"varint,1,opt,name=restriction_id,json=restrictionId,proto3" json:"restriction_id,omitempty"`
}

func (x *NearbyUserRestrictions) Reset() {
	*x = NearbyUserRestrictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyUserRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUserRestrictions) ProtoMessage() {}

func (x *NearbyUserRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUserRestrictions.ProtoReflect.Descriptor instead.
func (*NearbyUserRestrictions) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyUserRestrictions) GetRestrictionId() uint32 {
	if x != nil {
		return x.RestrictionId
	}
	return 0
}

type NearbyOutputData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *NearbyOutput `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NearbyOutputData) Reset() {
	*x = NearbyOutputData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyOutputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyOutputData) ProtoMessage() {}

func (x *NearbyOutputData) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyOutputData.ProtoReflect.Descriptor instead.
func (*NearbyOutputData) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyOutputData) GetData() *NearbyOutput {
	if x != nil {
		return x.Data
	}
	return nil
}

type NearbyOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceRestriction []*PlaceRestriction `protobuf:"bytes,1,rep,name=place_restriction,json=placeRestriction,proto3" json:"place_restriction,omitempty"`
	UserByPk         *NearbyUser         `protobuf:"bytes,2,opt,name=user_by_pk,json=userByPk,proto3" json:"user_by_pk,omitempty"`
}

func (x *NearbyOutput) Reset() {
	*x = NearbyOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyOutput) ProtoMessage() {}

func (x *NearbyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyOutput.ProtoReflect.Descriptor instead.
func (*NearbyOutput) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{4}
}

func (x *NearbyOutput) GetPlaceRestriction() []*PlaceRestriction {
	if x != nil {
		return x.PlaceRestriction
	}
	return nil
}

func (x *NearbyOutput) GetUserByPk() *NearbyUser {
	if x != nil {
		return x.UserByPk
	}
	return nil
}

type PlaceRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId       uint32 `protobuf:"varint,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	RestrictionId uint32 `protobuf:"varint,2,opt,name=restriction_id,json=restrictionId,proto3" json:"restriction_id,omitempty"`
}

func (x *PlaceRestriction) Reset() {
	*x = PlaceRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nearby_nearby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceRestriction) ProtoMessage() {}

func (x *PlaceRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_nearby_nearby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceRestriction.ProtoReflect.Descriptor instead.
func (*PlaceRestriction) Descriptor() ([]byte, []int) {
	return file_nearby_nearby_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceRestriction) GetPlaceId() uint32 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *PlaceRestriction) GetRestrictionId() uint32 {
	if x != nil {
		return x.RestrictionId
	}
	return 0
}

var File_nearby_nearby_proto protoreflect.FileDescriptor

var file_nearby_nearby_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x2f, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x26, 0x0a, 0x0b, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x0a, 0x4e, 0x65, 0x61, 0x72, 0x62,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4d, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x47, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x32, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x5f, 0x70, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x42,
	0x79, 0x50, 0x6b, 0x22, 0x54, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63,
	0x68, 0x2d, 0x41, 0x70, 0x70, 0x2f, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nearby_nearby_proto_rawDescOnce sync.Once
	file_nearby_nearby_proto_rawDescData = file_nearby_nearby_proto_rawDesc
)

func file_nearby_nearby_proto_rawDescGZIP() []byte {
	file_nearby_nearby_proto_rawDescOnce.Do(func() {
		file_nearby_nearby_proto_rawDescData = protoimpl.X.CompressGZIP(file_nearby_nearby_proto_rawDescData)
	})
	return file_nearby_nearby_proto_rawDescData
}

var file_nearby_nearby_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nearby_nearby_proto_goTypes = []interface{}{
	(*NearbyInput)(nil),            // 0: protobuf.NearbyInput
	(*NearbyUser)(nil),             // 1: protobuf.NearbyUser
	(*NearbyUserRestrictions)(nil), // 2: protobuf.NearbyUserRestrictions
	(*NearbyOutputData)(nil),       // 3: protobuf.NearbyOutputData
	(*NearbyOutput)(nil),           // 4: protobuf.NearbyOutput
	(*PlaceRestriction)(nil),       // 5: protobuf.PlaceRestriction
}
var file_nearby_nearby_proto_depIdxs = []int32{
	2, // 0: protobuf.NearbyUser.user_restrictions:type_name -> protobuf.NearbyUserRestrictions
	4, // 1: protobuf.NearbyOutputData.data:type_name -> protobuf.NearbyOutput
	5, // 2: protobuf.NearbyOutput.place_restriction:type_name -> protobuf.PlaceRestriction
	1, // 3: protobuf.NearbyOutput.user_by_pk:type_name -> protobuf.NearbyUser
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nearby_nearby_proto_init() }
func file_nearby_nearby_proto_init() {
	if File_nearby_nearby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nearby_nearby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nearby_nearby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nearby_nearby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyUserRestrictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nearby_nearby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyOutputData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nearby_nearby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nearby_nearby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nearby_nearby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nearby_nearby_proto_goTypes,
		DependencyIndexes: file_nearby_nearby_proto_depIdxs,
		MessageInfos:      file_nearby_nearby_proto_msgTypes,
	}.Build()
	File_nearby_nearby_proto = out.File
	file_nearby_nearby_proto_rawDesc = nil
	file_nearby_nearby_proto_goTypes = nil
	file_nearby_nearby_proto_depIdxs = nil
}
