// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: place/place.proto

package place

import (
	comment "github.com/Architech-App/PlateModel/comment"
	restriction "github.com/Architech-App/PlateModel/restriction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint32                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FoursquareId      string                          `protobuf:"bytes,2,opt,name=foursquare_id,json=foursquareId,proto3" json:"foursquare_id,omitempty"`
	PlaceRestrictions []*restriction.WrapRestrictions `protobuf:"bytes,3,rep,name=place_restrictions,json=placeRestrictions,proto3" json:"place_restrictions,omitempty"`
	PlaceComments     []*comment.WrapComment          `protobuf:"bytes,4,rep,name=place_comments,json=placeComments,proto3" json:"place_comments,omitempty"`
}

func (x *PlaceDB) Reset() {
	*x = PlaceDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_place_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceDB) ProtoMessage() {}

func (x *PlaceDB) ProtoReflect() protoreflect.Message {
	mi := &file_place_place_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceDB.ProtoReflect.Descriptor instead.
func (*PlaceDB) Descriptor() ([]byte, []int) {
	return file_place_place_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceDB) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlaceDB) GetFoursquareId() string {
	if x != nil {
		return x.FoursquareId
	}
	return ""
}

func (x *PlaceDB) GetPlaceRestrictions() []*restriction.WrapRestrictions {
	if x != nil {
		return x.PlaceRestrictions
	}
	return nil
}

func (x *PlaceDB) GetPlaceComments() []*comment.WrapComment {
	if x != nil {
		return x.PlaceComments
	}
	return nil
}

var File_place_place_proto protoreflect.FileDescriptor

var file_place_place_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1d, 0x72,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x44, 0x42, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x75, 0x72, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6f, 0x75, 0x72, 0x73, 0x71, 0x75, 0x61,
	0x72, 0x65, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x12, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x57, 0x72, 0x61, 0x70,
	0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x11, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x3c, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x57, 0x72, 0x61, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0d,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x74, 0x65, 0x63, 0x68, 0x2d, 0x41, 0x70, 0x70, 0x2f, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_place_place_proto_rawDescOnce sync.Once
	file_place_place_proto_rawDescData = file_place_place_proto_rawDesc
)

func file_place_place_proto_rawDescGZIP() []byte {
	file_place_place_proto_rawDescOnce.Do(func() {
		file_place_place_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_place_proto_rawDescData)
	})
	return file_place_place_proto_rawDescData
}

var file_place_place_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_place_place_proto_goTypes = []interface{}{
	(*PlaceDB)(nil),                      // 0: protobuf.PlaceDB
	(*restriction.WrapRestrictions)(nil), // 1: protobuf.WrapRestrictions
	(*comment.WrapComment)(nil),          // 2: protobuf.WrapComment
}
var file_place_place_proto_depIdxs = []int32{
	1, // 0: protobuf.PlaceDB.place_restrictions:type_name -> protobuf.WrapRestrictions
	2, // 1: protobuf.PlaceDB.place_comments:type_name -> protobuf.WrapComment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_place_place_proto_init() }
func file_place_place_proto_init() {
	if File_place_place_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_place_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_place_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_place_place_proto_goTypes,
		DependencyIndexes: file_place_place_proto_depIdxs,
		MessageInfos:      file_place_place_proto_msgTypes,
	}.Build()
	File_place_place_proto = out.File
	file_place_place_proto_rawDesc = nil
	file_place_place_proto_goTypes = nil
	file_place_place_proto_depIdxs = nil
}
